spring:
  application:
    name: eureka-server

server:
  port: 1000

eureka:
  server:
    # 关闭保护机制 生产环境建议开启
    enable-self-preservation: false
    # 间隔多久拉取服务注册信息 默认30秒
    eviction-interval-timer-in-ms: 5000
  instance:
    # 使用ip注册 已关闭
    prefer-ip-address: true
    ip-address: 127.0.0.1
    # 默认hostname注册 可修改为其他名称
    hostname: localhost
  client:
    # 是否同步其他eureka节点数据 单个时关闭
    register-with-eureka: false
    # 不注册自己
    fetch-registry: false
    service-url:
      # 默认交互地址 多个以逗号分隔
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/