server:
  port: 1002

spring:
  application:
    name: gateway-server
  # Redis
  redis:
    host: 127.0.0.1
    password:
    # 数据库索引 默认0
    database: 0
    port: 6379
    timeout: 10000

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

zuul:
  # 解决会话保持Cookie问题
  add-host-header: true
  # 解决重定向问题
  sensitive-headers: '*'
  routes:
    # 路由配置 2种方式皆可 配置serviceId与url
    auth:
      path: /auth/**
      #serviceId: oauth-server
      url: http://localhost:1003/oauth
    base:
      path: /base/**
      serviceId: base-server

# 多实例配置以举例 开头对应serviceId
#base-server:
#  ribbon:
#    listOfServers: http://localhost:8080/,http://localhost:8081/

# OAuth2客户端相关配置
security:
  oauth2:
    client:
      # 指定获取access token的URI
      access-token-uri: http://localhost:1003/oauth/token
      # 用户跳转去获取access token的URI
      user-authorization-uri: http://localhost:1003/oauth/authorize
      client-id: xcloud
      # 指定客户端client secret 默认随机
      client-secret: xcloud
      # 也可在此指定客户端允许的grant types
      authorized-grant-types:
    # OAuth2登录地址 默认/login
    sso:
      login-path: /login
    resource:
      loadBalanced: true
      user-info-uri: http://localhost:1003/user
      prefer-token-info: false
  # security忽略地址 ,分隔 作用与ignored.urls等同
  ignored:

# 忽略鉴权url 格式更加整齐清晰
ignored:
  urls:
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /*/v2/api-docs

# Swagger界面内容配置
swagger:
  title: XCloud Gateway API接口文档
  description: XCloud Gateway Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://blog.exrick.cn
  contact:
    name: Exrick
    url: http://blog.exrick.cn
    email: 1012139570@qq.com
